---
title: "p8105_hw5_tm2680"
author: "Tatini Mal-Sarkar"
date: "11/5/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(stringr)
library(purrr)
library(magrittr)
library(ggridges)
```

```{r long_data_load_tidy}
long_data = str_c("./data/", list.files(path = "./data")) 
read_long = function(x) {
  read_csv(x)
}

output = map_dfr(long_data, read_long, .id = "input") %>% 
  mutate(arm = str_sub(long_data, 8, 10),
         arm = replace(arm, arm == "con", "control"),
         arm = replace(arm, arm == "exp", "experimental")) %>% 
  mutate(number = str_sub(long_data, 12, 13)) %>% 
  mutate(id = str_c(arm, "_", number)) %>% 
  select(input, id, arm, number, everything()) %>% 
  gather(week_1:week_8, key = "week", value = "value") %>%
  janitor::clean_names() %>% 
  separate(week, into = c("drop_var", "week"), sep = "_") %>% 
  select(-drop_var) %>% 
  mutate(week = as.numeric(week))

output %>% 
  ggplot(aes(x = week, y = value, color = number)) +
  geom_line() +
  labs(
    title = "Spaghetti plot of observations over time",
    x = "Week",
    y = "Value"
  ) +
  scale_color_hue(name = "Subject") +
  facet_grid(~ arm)
```

Here is a faceted spaghetti plot showing observations for each subject over a period of 8 weeks. On average, it looks like the values for the experimental group increased over time, whereas the values stayed roughly the same for the control group.



